### PR TITLE
Some updates for Investigation, Study and Assay profiles

### PR DESCRIPTION
**Pull request by floWetzels**
This PR removes several properties of Assay from the profile that seem to be copied from Study, as they do not correspond to any ISA properties. An exception is the creator/performer of an assay. I kept it in there, since it is also part of an ARC Assay. See Issue https://github.com/nfdi4plants/isa-ro-crate-profile/issues/5 for details.

Furthermore, some Study and Investigation properties were changed from MUST to SHOULD.

@stuzart Could you have a look at this? I think we had some longer discussions about the MUST properties of Investigation, Study and Assay at the Hackathon, but in this form they fit with the ARC tools that export an RO-Crate.

I will probably add further changes for other issues (https://github.com/nfdi4plants/isa-ro-crate-profile/issues/4, https://github.com/nfdi4plants/isa-ro-crate-profile/issues/7, https://github.com/nfdi4plants/isa-ro-crate-profile/issues/9) regarding Investigation, Study and Assay to this PR as well.

### CODE REVIEW

**Review by stuzart — APPROVED** [review]
looks good

**Review by HLWeil — APPROVED** [review]
Could you add a sentence about the `uri`s in the PR description if questions arise later? 

Otherwise looks good to me!

**Comment by floWetzels** [comment]
The `filename` property of the ISA types has now been integrated as `url` for all three types. (https://github.com/nfdi4plants/isa-ro-crate-profile/issues/7 and https://github.com/nfdi4plants/isa-ro-crate-profile/issues/9)

**Comment by floWetzels** [comment]
The dates properties of the ISA types have also been adapted, see https://github.com/nfdi4plants/isa-ro-crate-profile/issues/4.

**Pull request merged**
