### PR TITLE
Updated title from headline to name in profile

### PR DESCRIPTION
**Pull request by floWetzels**
This PR updates the schema term for the ISA property `title`. Currently it is mapped to `headline`. However, the RO-Crate specification requires the root data entity to have a `name` specified (see https://github.com/nfdi4plants/ARCtrl/issues/472). The Google Dataset Search also shows the title of a dataset through this property. Thus, this PR updates the profiles for Investigation and Study accordingly.

### CODE REVIEW

**Comment by HLWeil** [comment]
I understand the need for such a change, but just to make sure: If you look into non-ARC datasets in the Google Dataset search, what kind of `names` are they using? Would this match semantically with our `Titles`?

**Comment by floWetzels** [comment]
It's inconsistent, I don't see a strict pattern. But I would say that most names are in the style of titles.

**Review by HLWeil — APPROVED** [review]

**Comment by floWetzels** [comment]
@HLWeil What do you think of the description I added to the mapping file?

**Comment by HLWeil** [comment]
Looks good!

**Pull request merged**
